### ISSUE TITLE
Example needed for stand alone app on github

### ISSUE THREAD

**Issue by f34rdotcom** [SmartThingsCommunity/st-device-sdk-c-ref#40]
I have been putting my code in st-device-sdk-c-ref/apps/esp32_v4.x/AlarmDecoder-STSDK folder for testing and designing my device code. This is not optimal for putting a project on github. I need some help integrating into this build environment for my own project.

Thanks for any help!

Best
 SM

**Comment by hdlee27** [comment]
If 'AlarmDecoder-STSDK' is stand alone app, there is no path for that stand alone app in 'st-device-sdk-c-ref' yet.

Support for stand alone app in 'st-device-sdk-c-ref' should be considered,
but, 'st-device-sdk-c-ref' supports esp32/esp8266/rtl8195/rtl8720c/rtl8721c/emw3166 at this time

If you want to build stand alone app by using st-device-sdk-c-ref build system now, you can write 'st-device-sdk-c-ref/tools/[BSP_NAME]/build_[BSP_NAME].sh'.
Because 'st-device-sdk-c-ref/build.sh' use 'st-device-sdk-c-ref/tools/[BSP_NAME]/build_[BSP_NAME].sh' to build 'st-device-sdk-c-ref/apps/[BSP_NAME]/[APP_NAME]'.
